name: Build
on:
  push:
    branches:
      - master

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: get dependencies
        run: yarn
      - name: test
        run: echo $PWD
      - name: test 2
        run: ls
      - name: build
        run: yarn build